### ISSUE TITLE
Do not use deprecated async.signal in the tests

### ISSUE THREAD

**Issue by fthomas** [scalaz/scalaz-stream#310]
`AsyncSignalSpec` and `MergeNSpec` still make use of the deprecated `async.signal`. I guess they should be rewritten with `async.signalOf`.

**Comment by djspiewak** [comment]
I left `AsyncSignalSpec` the way it was since it's actually testing `signal` directly.  Though, given that `signal` is deprecated, it probably makes more sense to just remove those tests.

`MergeNSpec` was trickier.  I tried to rewrite it to use `signalOf`, but the tests actually rely on the bizarre behavior of a non-valued signal.

**Comment by pchlupacek** [comment]
I think with recent change to signal, we can just rename the async.signal to async.signalUnset and close this?
