### ISSUE TITLE
Process#toTask does not support equational reasoning

### ISSUE THREAD

**Issue by djspiewak** [scalaz/scalaz-stream#315]
See [here](https://github.com/scalaz/scalaz-stream/blob/master/src/main/scala/scalaz/stream/Process.scala#L981) for why.  The essence of the symptoms here are that you can call `toTask` on a `Process` and run it repeatedly, getting *different* results from what would have happened if you call `toTask` multiple times.  Specifically, the following two functions are *not* equivalent:

```scala
def foo[A](p: Process[Task, A]): Task[A] = p.toTask >> p.toTask

def bar[A](p: Process[Task, A]): Task[A] = {
  val step = p.toTask
  step >> step
}
```

For reasons that should be obvious, this is annoying.  Is it intentional?  I think that this is pretty simple to fix by throwing a `Task delay` around the current body of `toTask`, then `join` at the end.

**Comment by djspiewak** [comment]
Here's an example snippet that demonstrates a `Process` where you can run into trouble:

```scala
import scalaz.concurrent._
import scalaz.stream._
import scalaz.syntax.monad._
 
import java.util.concurrent.atomic.AtomicInteger
 
val i = new AtomicInteger
val src = Process eval (Task delay { i.getAndIncrement() })
val p = src.fold(2) { _ * _ }
 
println((p.toTask >> p.toTask).run)
 
i.set(0)
 
val step = p.toTask
println((step >> step).run)
```

**Comment by alissapajer** [comment]
This issue is effectively exposing the `var` that's inside the impl of `toTask`. This `var` should remain private to `toTask` at all costs, but as @djspiewak pointed out, the since `toTask` isn't wrapped in a `Task`, this `var` is initiated when `toTask` is called rather than when it is run.

The entirety of any function returning a `Task` should be inside `Task` to avoid issues like this. 

In short, +1 to the change.

**Comment by alissapajer** [comment]
@djspiewak I was just reading backlogs on gitter. If I see a method that returns a `Task` I assume referential transparency. Do you have a concrete example of how `toTask` is no longer useful when you wrap it all up in a `Task` (i.e. when it's not referentially transparent).

**Comment by dcsobral** [comment]
To sum up some discussion that happened on gitter, there's an intentional
side effect happening with toTask. It is _supposed_ to "grab the next"
output of a Process. However, that's not the only side effect going on.
There are two:

* (Re)starting the Stream
* Reading the next element

Perhaps a better signature would be Task[Task[T]], where both effects are
represented.

For my part, I have always hated the name, precisely because it does
something much more like Task[Task[T]] than Task[T]. It has much more in
common with the run* methods, so I'd pick something like runTask for it,
and deprecate the current toTask.


On 13 February 2015 at 05:57, Alissa Pajer <notifications@github.com> wrote:

> @djspiewak <https://github.com/djspiewak> I was just reading backlogs on
> gitter. If I see a method that returns a Task I assume referential
> transparency. Do you have a concrete example of how toTask is no longer
> useful when you wrap it all up in a Task (i.e. when it's not
> referentially transparent).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scalaz/scalaz-stream/issues/315#issuecomment-74249576>
> .
>



-- 
Daniel C. Sobral

I travel to the future all the time.

**Comment by djspiewak** [comment]
I'd be happy to take care of this if no one has any objections.  To be clear, the implementation of `runTask` (or `stepTask`, which I think might make a bit more sense as a name) would be identical to the existing one, except with a `Task delay` thrown around the whole thing.  There would be no flattening of the effects, and thus the result type would be `Task[Task[A]]`.
