### ISSUE TITLE
Release a version for Scala 2.12.0-M1

### ISSUE THREAD

**Issue by etorreborre** [scalaz/scalaz-stream#382]
I need this version to be able to publish specs2 as well, thanks.

**Comment by djspiewak** [comment]
I can handle the porting (if necessary), but only @pchiusano can actually push a release.

**Comment by fthomas** [comment]
I think it would be beneficial if not only @pchiusano could push releases. That would also help with #258.

**Comment by pchiusano** [comment]
Apologies for being MIA, have been super wrapped up in other work, though I
still should have communicated better. :/ I should have time to work on
things next week. And yes I'd like to remove myself as a bottleneck from
doing releases. :)

There's also a large backlog of issues that I'd like to prioritize and turn
into a roadmap. Will look for folks on gitter and start going through
issues next week.

**Comment by djspiewak** [comment]
As an FYI, we need builds targeting 2.12 for the following two packages in order to push one for scalaz-stream:

- scalacheck (attn @rickynils)
- scodec-bits (attn @mpilquist)

**Comment by etorreborre** [comment]
Scodec is [ready](https://oss.sonatype.org/content/repositories/releases/org/scodec/scodec-core_2.12.0-M1/1.8.1).

Scalacheck is [ready too](https://oss.sonatype.org/content/repositories/releases/org/scalacheck/scalacheck_2.12.0-M1/1.12.4/).

**Comment by djspiewak** [comment]
@etorreborre Thanks for the heads up!  I'll get a branch for this asap, though we'll have to wait for @pchiusano to push a release.

**Comment by djspiewak** [comment]
So I attempted to do the upgrade, and I got stymied by the combination of a) what seems to be an infinite loop in our tests, and b) a regression in ScalaCheck where tests no longer produce output in SBT.  The test that seems to be looping *appears* (based on thread dumps) to be `WyeSpec`, but it's hard to be certain.  The bug is reproducible on both 2.12-M1 and 2.11.7, so I think it's probably ScalaCheck's fault and not Scala's.

If someone wants to take a look and/or offer any tips, my wip branch is [here](https://github.com/djspiewak/scalaz-stream/tree/wip/scala-2.12).

**Comment by fiadliel** [comment]
I'm not sure why ScalaCheck is going off the rails here, but changing the test definition from `class` to `object` in `WyeSpec.scala` stops the looping (and this is the style suggested in all the ScalaCheck documentation). Though I note that the commit that made this change was a0d4862cfeb8e9597a3be608b31f600b439f7159 to fix object init deadlocks...

And here's a stacktrace from the repeated execution of the first property in WyeSpec: https://gist.github.com/fiadliel/732b9b5a56158619bcdc

**Comment by fiadliel** [comment]
It looks like for _each property_ in a class, the class is instantiated again, _all_ `secure { ... }` blocks are evaluated, and... for WyeTest, that's going to be slooooowwww.

**Comment by fiadliel** [comment]
Behaviour changed in https://github.com/rickynils/scalacheck/commit/82042613eebbde3c822328cbfab3c4186828f1f1

In lieu of an upstream change, wrapping property definitions in `Prop.protect` helps a lot.

**Comment by fiadliel** [comment]
Pull request (just for the scalacheck update) here: https://github.com/scalaz/scalaz-stream/pull/417

**Comment by djspiewak** [comment]
Wanted to pop in here to give an update…

Obviously #418 is the branch that updates the raw dependencies to 2.12.  I'll be merging that later today, since the TravisCI failure on that PR is spurious.  Also happening later today is a change-over to Maven Central as our primary repository!  So basically, #258.  To be clear: **scalaz-stream will still be available on bintray**.  You won't have to change anything in your builds, but you will no longer need to add the Scalaz bintray to use scalaz-stream in new projects, and downstream projects will be eligible for inclusion in Maven Central.

Here's the kicker for this particular issue: when we push the release to Sonatype, we will also be pushing a 2.12 cross-build.  So in other words, killing three birds with a small pile of gravel, but killing them nonetheless.

**Comment by etorreborre** [comment]
Thanks @djspiewak!

**Comment by djspiewak** [comment]
Version 0.7.2/0.7.2a is now released (and in Maven Central, no less!) with a 2.12.0-M1 cross-build.  I wanted to include M2 as well, but scodec-bits hasn't pushed a cross-build for M2 yet.  At least, not so far as I can find at 1am.  It's easy enough for me to push a separate cross-build tomorrow if we can find one…

**Comment by SethTisue** [comment]
scodec-bits is now available for 2.12.0-M2: https://search.maven.org/#artifactdetails%7Corg.scodec%7Cscodec-bits_2.12.0-M2%7C1.0.9%7Cbundle

**Comment by djspiewak** [comment]
Yep!  I pushed 0.7.2/0.7.2a for 2.12.0-M2 this morning.

**Comment by SethTisue** [comment]
oh, I see now over at https://github.com/etorreborre/specs2/issues/399 you guys are already all over this :-)
