### ISSUE TITLE
surprising behavior in Process Monad?

### ISSUE THREAD

**Issue by refried** [scalaz/scalaz-stream#423]
Here's the top-level process:
```scala
def scanOneFile(input: File): Process[Task, Unit] =
  Process.eval_(Task(println(s"entering scanOneFile($input)"))) ++
  actualWork(input) ++
  Process.eval_(Task(println(s"exiting  scanOneFile($input)")))

List("file1", "file2", "file3", "file4").map { input ⇒
  val f = new File(input)
  scanOneFile(f)
}.sequenceU.run.run
```

I was expecting output like this:
```
entering scanOneFile(file1)
exiting  scanOneFile(file1)
entering scanOneFile(file2)
exiting  scanOneFile(file2)
entering scanOneFile(file3)
exiting  scanOneFile(file3)
entering scanOneFile(file4)
exiting  scanOneFile(file4)
```

But instead saw output like this (linefeeds added for emphasis): 
```
entering scanOneFile(file1)
entering scanOneFile(file2)
entering scanOneFile(file3)
entering scanOneFile(file4)

exiting  scanOneFile(file4)
exiting  scanOneFile(file3)
exiting  scanOneFile(file2)

entering scanOneFile(file2)
entering scanOneFile(file3)
entering scanOneFile(file4)

exiting  scanOneFile(file4)
exiting  scanOneFile(file3)
exiting  scanOneFile(file2)
exiting  scanOneFile(file1)
```

As a work-around, I'm using:
```scala
List("file1", "file2", "file3", "file4").foreach { input ⇒ 
  val f = new File(input)
  scanOneFile(f).run.run
}
```

P.S. If I simplify further:
```scala
def foo(input: String): Process[Task, Unit] =  Process.eval_(Task(println(s" ** $input")))

List("file1", "file2", "file3", "file4").map(foo).sequenceU.run.run
```
I'd expect to see
```
 ** file1
 ** file2
 ** file3
 ** file4
```
but I only get:
```
 ** file1
```
and nothing for the other three files.  Not sure if this is normal.

**Comment by alissapajer** [comment]
Hi @refried 

Based on your original expected output, try it this way:

```scala
def doThings(input: String): Task[Unit] = 
  Task.delay(println(s"entering scanOneFile($input)")) >>
  Task.delay(println(s"exiting  scanOneFile($input)"))

val scanOneFile: Sink[Task, String] = sink.lift(doThings _)

val files0 : List[String] = List("file1", "file2", "file3", "file4")
val files: Process[Task, String] = Process.emitAll(files0)

files.through(scanOneFile).run.run
```
generates the output:
```scala
scala> files.through(scanOneFile).run.run
entering scanOneFile(file1)
exiting  scanOneFile(file1)
entering scanOneFile(file2)
exiting  scanOneFile(file2)
entering scanOneFile(file3)
exiting  scanOneFile(file3)
entering scanOneFile(file4)
exiting  scanOneFile(file4)
```
(Side note: if you want to echo the original output of your process, use `observe` instead of `through`.)

When you're using `sequence` and `traverse`, the traversal isn't "linear" in the way that you were expecting. In order to obtain a "linear" traversal in streams, a `Sink` is the tool you'd want, defined [here](https://github.com/scalaz/scalaz-stream/blob/master/src/main/scala/scalaz/stream/package.scala#L36).

If `files0` were instead of type `List[Task[String]]` (when for example you want the creation of the `String`s or `File`s to happen when the `Process` is run and not sooner), then `val files = Process.emitAll(files0).eval` would be what you want.

As an aside, here's an interesting `traverse` example:
```scala
scala> List(1,2,3).traverse(x => { val res = List(x, x + 1); println(s"$res"); res })
List(3, 4)
List(2, 3)
List(1, 2)
res58: List[List[Int]] = List(List(1, 2, 3), List(1, 2, 4), List(1, 3, 3), List(1, 3, 4), List(2, 2, 3), List(2, 2, 4), List(2, 3, 3), List(2, 3, 4))
```

In your second example: 
```scala
def foo(input: String): Process[Task, Unit] =  Process.eval_(Task(println(s" ** $input")))
List("file1", "file2", "file3", "file4").map(foo).sequenceU.run.run
```
you've hit the interesting case that differentates `Process.eval_` and `Process.eval`. If you instead have:
```scala
def foo(input: String): Process[Task, Unit] =  Process.eval(Task(println(s" ** $input")))
```
then the output will be as you expected, namely:
```scala
scala> List("file1", "file2", "file3", "file4").map(foo).sequenceU.run.run
 ** file1
 ** file2
 ** file3
 ** file4
```
This is because a `Process.eval_` emits no values. And so when you `flatMap` over a  `Process.eval_`, there is no emitted value to provide as the input to the `flatMap` function.

Consider the following example. The process `Process.eval_(Task.delay(println("hi")))` will not emit a value, meaning that the process that's supposed to print `"hi again"` will never be run because the function that calls it will never be called.
```scala
scala> Process.eval_(Task.delay(println("hi"))) flatMap { _ => Process.eval_(Task.delay(println("hi again"))) }
res52: scalaz.stream.Process[[x]scalaz.concurrent.Task[x],Nothing] = Await(scalaz.concurrent.Task@67037ed7,<function1>)

scala> res52.run.run
hi
```
versus
```scala
scala> Process.eval(Task.delay(println("hi"))) flatMap { _ => Process.eval(Task.delay(println("hi again"))) }
res54: scalaz.stream.Process[[x]scalaz.concurrent.Task[x],Unit] = Await(scalaz.concurrent.Task@64c3c58a,<function1>)

scala> res54.run.run
hi
hi again
```

It's worth noting that the "innermost" `Process` in a `flatMap` (in this example) could very well be a `Process.eval_` because we are not attempting to use the value it emits (or doesn't). 

Also, in this second example, as in the first, I'd again use a `Sink` instead of a `sequence`.

**Comment by refried** [comment]
Thanks @alissapajer.  I think I understand what you said about the second example, but not about the first:   What did you mean by "linear"?  I don't mind if they are in reverse order or something, like in the List traversal example you showed, but I was surprised that files 2, 3, 4 were entered and exited twice instead of once, know what I mean?

P.S. I only have the `println`s in there for debugging; I want to make `actualWork` evaluate exactly once for each of the inputs.  (`actualWork` is a `Process`, not a `Task`.)

**Comment by refried** [comment]
For now, instead of:
```scala
(files: List[String]).map(new File(_)).map(scanOneFile).sequenceU.run.run
```
which produces:  (output simplified; each number represents an "enter")
```
1
2
3
4
2
3
4
```
with three unexpected evaluations,

I'm using:
```scala
Process.emitAll(files: List[String]).map(new File(_)).flatMap(scanOneFile).run.run
```
which produces
```
1
2
3
4
```

**Comment by alissapajer** [comment]
PART I:
___________________________________________
@refried The unexpected duplicated output you saw is coming from the implementation of `scanOneFile`. See PART II below for exact details on why that is. 

As PART II shows, it would be better to get your example working using `Sink`. So, referring to your original example, you said that "`actualWork` is a `Process`, not a `Task`", which I think may be making an implementation using `Sink` tricky. If you want to reply with a rough implementation of `actualWork` and/or `scanOneFile` we can look at how to use a `Sink` in that situation.

What I meant by "linear" before was the following. `Process` in scalaz-stream follows a pull model, meaning that when a `Process` is run at the end of the world, the elements are pulled through one by one. It was this one-by-one movement that I had in mind when I used the word "linear". In scalaz-stream, this "linear" movement is relatively transparent, meaning that the mental model of one item after the next being pulled through the pipeline is pretty accurate.

A bit about `Sink`. A `Sink` is really just a `Process` of functions that perform effects:
```scala
type Sink[Task, A] = Process[Task, A => Task[Unit]]
```
When we send a `Process[Task A]` `through` (an alias for `to`) a `Sink[Task, A]`, the function `A => Task[Unit]` is applied to each element `A` such that when everything is eventually `run`, those `Task[Unit]` effects will also be run. In your example, `A` would possibly be `File`.

In terms of mental models of scalaz-stream: I think about a `Task` being `run`, meaning that the effect it represents will actually happen when the `Task` is `run`, but not sooner. But `Process` is a different model from `Task` in that a `Process` creates a pipeline through which your data will be pulled, with effects (`Task`s) being `run` along the way.

PART II:
___________________________________________
So, why exactly the duplicate outputs you see when you use `sequenceU`? Let's consider an example with two files instead of four so we have less output.
```scala
def scanOneFile(input: File): Process[Task, Unit] =
  Process.eval(Task(println(s"entering scanOneFile($input)"))) ++
  Process.eval(Task(println(s"exiting  scanOneFile($input)")))
```
with output:
```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

List("file1", "file2").map { input ⇒
  println(s"got input $input")
  val f = new File(input)
  scanOneFile(f)
}.sequenceU.run.run

// Exiting paste mode, now interpreting.

got input file1
got input file2
entering scanOneFile(file1)
entering scanOneFile(file2)
exiting  scanOneFile(file2)
exiting  scanOneFile(file1)
entering scanOneFile(file2)
exiting  scanOneFile(file2)
```
The question being: why the extra "entering" and "exiting" of "file2"?

First consider `scanOneFile`. This is a `Process` that will emit *two* elements, one of which prints "entering" the other which prints "exiting". We can rewrite the `sequenceU` bit as follows:
```scala
scala> scanOneFile(new File("file1")) flatMap { _ => scanOneFile(new File("file2")) }
res3: scalaz.stream.Process[[x]scalaz.concurrent.Task[x],Unit] = Append(Await(scalaz.concurrent.Task@2eb7322b,<function1>),Vector(<function1>))

scala> res3.run.run
// first output from scanning file1, followed by a full scan of file2
entering scanOneFile(file1)
entering scanOneFile(file2)
exiting  scanOneFile(file2)
// second output from scanning file1, followed by a second full scan of file2
exiting  scanOneFile(file1)
entering scanOneFile(file2)
exiting  scanOneFile(file2)
```
Same duplicated output. Why? Consider `scanOneFile(new File("file1"))`. This is a process that will emit *two* elements! Each of those elements in turn is passed to `flatMap`, which means that `scanOneFile(new File("file2"))` will be run twice, producing the duplicate print results for "file2". When you have more files, this effect increase exponentially. Meaning: "file1" is scanned 1 time (2^0), "file2" is scanned 2 times (2^1) and "file3" is scanned 4 times (2^2).
```scala
scala> scanOneFile(new File("file1")) flatMap { _ => scanOneFile(new File("file2")) flatMap { _ => scanOneFile(new File("file3")) } }
res1: scalaz.stream.Process[[x]scalaz.concurrent.Task[x],Unit] = Append(Await(scalaz.concurrent.Task@38dc507,<function1>),Vector(<function1>))

scala> res1.run.run
entering scanOneFile(file1)
entering scanOneFile(file2)
entering scanOneFile(file3)
exiting  scanOneFile(file3)
exiting  scanOneFile(file2)
entering scanOneFile(file3)
exiting  scanOneFile(file3)
exiting  scanOneFile(file1)
entering scanOneFile(file2)
entering scanOneFile(file3)
exiting  scanOneFile(file3)
exiting  scanOneFile(file2)
entering scanOneFile(file3)
exiting  scanOneFile(file3)
```
Short of it being, when you `flatMap` over a `Process` that contains more than one element, the effects will be evaluated multiple times, which is not what's desired. A `Sink` solves this problem by instead providing a way to control your desired effects so that they will only be evaluated *once* per item.

**Comment by refried** [comment]
@alissapajer Wow that is super helpful, thank you.  I guess I need to practice thinking about what's getting emitted from a `Process`.

**Comment by djspiewak** [comment]
@alissapajer Intense.  :-D  I'm going to mark this as closed for now.
