### ISSUE TITLE
Release 0.7.3a

### ISSUE THREAD

**Issue by runarorama** [scalaz/scalaz-stream#427]
Can somebody with the appropriate permissions cut a release of the current series 0.7a? @pchlupacek? I don't think there are any binary incompatibilities, but it would be good to get another pair of eyes to verify that.

**Comment by pchlupacek** [comment]
s sorry  @runarorama . was cut from the interente for past 7 days, and still with limitted access. will try to do it asap

**Comment by pchlupacek** [comment]
@runarorama was published. I believe there is a delay tho before it will show on maven central. @djspiewak  any guess how long this will take? Just followed your tutorial, no errors, so this shall be imho just question of time before this will appear.

**Comment by pchlupacek** [comment]
@djspiewak Also note that I was not able to publish 0.7.3 for Scala 12, hence scalaz-core seems to be missing for M1 and M2 builds, so I just published S10, S11 versions. When the M1/M2 build for 7.0.8 will be available we can perhaps add them to maven central too.

**Comment by djspiewak** [comment]
@pchlupacek You should look at `series/0.7` and `series/0.7a` again.  I published 0.7.2 for Scala 2.12, and scalaz-core dependencies were available.  We need to make sure we maintain those cross-builds, because downstream projects are depending on them now (notably specs2).

**Comment by pchlupacek** [comment]
@djspiewak this is what I am getting 
```
[error] (*:update) sbt.ResolveException: unresolved dependency: org.scalaz#scalaz-core_2.12.0-M1;7.0.8: not found
[error] unresolved dependency: org.scalaz#scalaz-concurrent_2.12.0-M1;7.0.8: not found
[error] unresolved dependency: org.scalaz#scalaz-scalacheck-binding_2.12.0-M1;7.0.8: not found
```

**Comment by djspiewak** [comment]
@pchlupacek Check out 185044376fc2d880f7cafe10ae2fbcd2e1fb6a16.  I published from that commit.  Unless the artifacts were yanked (in which case, *major* shame on the scalaz team), there should be no problem with 7.0.8 and *both* M1 and M2.

**Comment by djspiewak** [comment]
@pchlupacek After a quick search on Maven Central, it looks like 7.0.8 is published for M2 and 7.0.7 is published for M1.  Annoying that there is no one artifact for both, but easy to resolve.

In future, if artifacts do not resolve for a particular cross-build, do *not* publish the release!  We basically now have to go back and publish a 0.7.3.1/a or similar in order to get the dependencies to line up universally.  It would have been easier if 0.7.3 hadn't already been half-published.

**Comment by pchlupacek** [comment]
@djspiewak you sure you cannot publish just the M1/M2 releases under 0.7.3(a)?  I mean if you do your steps w/o `+` it shall be easily doable?

**Comment by pchlupacek** [comment]
I am also not sure if we shall block the release versions with milestone versions. I'd rather see them as eventually snapshots?

**Comment by xuwei-k** [comment]
Shall I publish `"scalaz-core_2.12.0-M1" % "7.0.8"`?  Please let me know if you have any trouble of `scalaz-core` and `scalaz-concurrent` dependencies :)

**Comment by djspiewak** [comment]
@pchlupacek We can, but it does require @xuwei-k to publish 7.0.8 for M1.  We can also change the build.sbt to use 7.0.7 on M1 and 7.0.8 everywhere else, but that's a pain because it pushes us to a different version (i.e. my steps would *not* work; you'd have to manually override the version).

Milestone cross-builds are part of the release, IMO.  The entire community is trying to sort itself out to get its ducks in order for the 2.12 release, and unfortunately (fortunately?) we're downstream of a LOT of projects at this point.  It's worth holding a release in order to get it right.

**Comment by pchlupacek** [comment]
Yeah, see your point. Perhaps tho, we can have `(b)` releases for these crossbuilds (like we have (a) for scalaz version? That will allow release versions to be just always up to date, and we may for early adopters of S12 have separate branch/publish lifecycle making sure all dependencies are ready? 

Anyhow not sure what I have to do now with M1/M2 do you have any suggestions?

Also wondering if we shouldn't just bump master and make 0.8?

**Comment by djspiewak** [comment]
@pchlupacek Having `b` releases for M1/M2 basically defeats the purpose of the cross-build mechanism, since it means that users would need to have conditional logic in their `build.sbt` in order to use the appropriate version.

So the absolute best-case scenario for 0.7.3 and M1/M2 is if @xuwei-k pushes 7.0.8 for M1.  At that point, we should be able to just push M1 and M2 releases from our existing tag.

I'd definitely like to do an 0.8 soon.  Obviously 0.7.3 is kind of a separate issue, since 0.8 breaks some compatibility and requires users to alter their code, whereas 0.7.3 is drop-in.

**Comment by pchlupacek** [comment]
@xuwei-k can you please comment on that so we can see if you will be able to make 7.0.8 for M1? Thannks

**Comment by xuwei-k** [comment]
I just released scalaz 7.0.8 for Scala 2.12.0-M1
- http://repo1.maven.org/maven2/org/scalaz/scalaz-core_2.12.0-M1/7.0.8/
- http://repo1.maven.org/maven2/org/scalaz/scalaz-concurrent_2.12.0-M1/7.0.8/

**Comment by pchlupacek** [comment]
Thanks @xuwei-k A lot!

**Comment by runarorama** [comment]
Where does this put us with streams 0.7.3?

**Comment by pchlupacek** [comment]
they are released now except for M1/M2 release. You need M1/M2? Was hoping to get look on publishing M1/M2 laters this week but for all other is already published

**Comment by runarorama** [comment]
Awesome, thanks!
