### ISSUE TITLE
Do 0.8 release?

### ISSUE THREAD

**Issue by pchiusano** [scalaz/scalaz-stream#430]
Just wanted to start a thread to discuss the following:

* The new design is not fully baked yet.
* In the meantime, do we want to do a 0.8 release off of master?
* If so, is there anything in progress we are waiting on, or can we branch and cut a release anytime?
* If we are doing a 0.8 release, what else needs to be done before that can happen? (Release notes, other stuff..?)

I don't have strong feelings about this and would like to stay focused on the redesign work myself. But I have no objections to someone else managing a release off current master.

**Comment by djspiewak** [comment]
The main thing I'd like to get into 0.8 that isn't done yet (because it was held in suspension due to the uncertainty over the redesign) is the rework of `Kill`.  This is one of those things that would have a pretty direct impact on day job stuff, so I'd like to get it done and in before we do a release.  I can probably do it this weekend though.

Beyond that, release notes, merging/reviewing some PRs, etc.  I'd like to land MiMa for 0.8 as well so that we can start being a bit more disciplined about compatibility.  I can take point on the release, @pchiusano, so you can stay focused on the redesign.  I still haven't had a chance to review that branch, so I wouldn't be much help there just yet anyway.

**Comment by pchiusano** [comment]
Sounds good to me.

**Comment by pchlupacek** [comment]
+1

**Comment by shawjef3** [comment]
@djspiewak If you need help getting a release out, let me know. You mentioned somewhere that you've been too busy. I can request permission to publish to maven central under org.scalaz, merge the merge requests you want, run the tests, and publish.

**Comment by pchiusano** [comment]
Current status of this?

**Comment by djspiewak** [comment]
Status: **done**.  [Release notes](https://github.com/scalaz/scalaz-stream/wiki/0.8)  I tried to thoroughly explain the two major breaking changes.  Very sorry for all the delays on this.  It's been a busy month...

**Comment by pchiusano** [comment]
Nice!! Thanks Daniel.
